### ISSUE TITLE
Was this inspired from symfony/thanks ?

### ISSUE THREAD

**Issue by OwlyCode** [feross/thanks#30]
Hi there !

This project reminds me of https://github.com/symfony/thanks . Was it inspired from it ? If so it should thank it !

Great job bringing thanks to the npm world !

**Comment by feross** [comment]
Nope, I hadn't heard of `symfony/thanks` before making this project.

I chose the name `thanks` because @mafintosh, @karissa, and a few other friends of mine started a project to share wifi passwords that we never shipped. It was gonna be called thanks. Actually the repo is still online, lol: https://github.com/moose-team/thanks

When brainstorming names for this, my friend @dcposch actually suggested `thanks` and then I asked @mafintosh to let me use it, and he kindly obliged :)
